### PR TITLE
Make SourceMappingsService and related jar processors work in deobf

### LINKED ISSUE #1486: Mod-provided javadoc fails to apply when obfuscation is disabled
It's passed to the decompiler using a mapping file, but the mapping service is not used when `disableObfuscation` is active:
https://github.com/FabricMC/fabric-loom/blob/114028339186b041fb9eac5995750b005495ac37/src/main/java/net/fabricmc/loom/task/GenerateSourcesTask.java#L224-L227

### PR DESCRIPTION
**Pull request by Juuxel**
Fixes #1486. The test for this fix is in the earlier PR #1487.

### CODE REVIEW

File: src/main/java/net/fabricmc/loom/task/service/SourceMappingsService.java [hunk 1]
```diff
@@ -87,16 +90,33 @@ public static Provider<Options> create(Project project) {
 	private static Path getMappings(Project project, Property<String> hashProperty) {
 		final LoomGradleExtension extension = LoomGradleExtension.get(project);
 		final MinecraftJarProcessorManager jarProcessor = MinecraftJarProcessorManager.create(project);
+		final Path dir = extension.getFiles().getProjectPersistentCache().toPath().resolve("source_mappings");
+		final Path emptyMappingsPath = dir.resolve("empty.tiny"); // empty base mappings for unobf
```
Comment (Juuxel) [inline src/main/java/net/fabricmc/loom/task/service/SourceMappingsService.java:94]: Note: When implementing proper deobf javadoc support (annotater), this empty mapping file should be replaced with those javadoc mappings.

**Review by modmuss50 — APPROVED** [review]

**Comment by modmuss50** [comment]
Great thanks :)
