### PR TITLE
Rewrite the internals of mod configuration remapping to fix bugs

### LINKED ISSUE #572: Depending on a mod with transitive non-mods deps exposes those deps in pom.xml
For example, if a mod depends on Fabric Language Kotlin with `modImplementation`, its POM will contain
- A `runtime` dep on FLK as expected
- **Extra `runtime` deps on...**
  - kotlin stdlib modules
  - kotlinx-serialization
  - kotlin-reflect

when set up normally with software components.

This happens because we add the non-mod artifacts from `mod*` configs into the standard configs - like `implementation` - directly. Not sure what a good fix would be, though.

### LINKED ISSUE #801: Weird behavior with compileOnlyApi dependencies of mod dependencies
I have a mod library ([`cloud-fabric`](https://github.com/Incendo/cloud)) that declares a `compileOnlyApi` dependency on `org.apiguardian:apiguardian-api:1.1.2` (not a mod). When adding `cloud-fabric` to `modImplementation` in a separate project, it seems like the `compileOnlyApi` dependency isn't properly pulled in, as evidenced by the output of build scans/dependencies task, and the massive amount of warnings on build: https://github.com/jpenilla/squaremap/actions/runs/3762624455/jobs/6395483461#step:7:131
(adding the dependency to `compileOnly` manually is a workaround, which I've since used in the linked repo)

I also have non-mod libraries (for example `cloud-paper`), which declares the same `compileOnlyApi` dependency, and when depending on it using `implementation` in a separate project, I get no similar warnings and the dependency appears in scans/dependencies as expected, which is what leads me to think it's something with loom.

I've spent some time trying to debug this but haven't really gotten anywhere.

`cloud.commandframework:cloud-fabric:1.8.0` is published on maven central, adding it to `modImplementation` is enough to reproduce the issue, to get the warnings just reference an annotated method (for example `StringArgument.builder("");`) (might also need `-Xlint:all`, not sure as I always have it on)

*Every* module in cloud has this `compileOnlyApi` dep, which means not only is the direct dependency lost, but also the dependencies of for example `cloud-core` that `cloud-fabric` also depends on.

### PR DESCRIPTION
**Pull request by Juuxel**
Fixes #801. Fixes #572.

Needs a bit of testing, esp. with split builds and split dependencies.

- Loom now remaps mods to "collector configs" that are specific to the execution type (compile-time/API vs runtime).
  - For example, `modImplementation` remaps to `modCompileClasspathMain` and `modRuntimeClasspathMain`.
  - This lets us use Gradle's `org.gradle.usage` attributes to select whether it's a compile-time or runtime dependency
  - Note: Remap configurations sourcing from `api` are partially left intact due to their special logic in the `namedElements` configuration.
- Setting the proper usages fixes #801.
- No dependency files are added to the real target configurations (like `api` and `implementation`) anymore.
  - This fixes #572, since `runtimeClasspath` and `compileClasspath` don't leak transitive dependencies unlike `implementation` etc.

### CODE REVIEW

File: src/main/java/net/fabricmc/loom/util/Strings.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+ * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+ * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+ * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
+ * SOFTWARE.
+ */
+
+package net.fabricmc.loom.util;
+
+public final class Strings {
+	public static String capitalize(String word) {
```
Comment (Juuxel) [inline src/main/java/net/fabricmc/loom/util/Strings.java:28]: I couldn't find this in any libraries and didn't want to pull in another one, let me know if there is a library that we already have that has it

Comment (modmuss50) [reply src/main/java/net/fabricmc/loom/util/Strings.java:28]: I think this is fine, I dont see any existing library usage. You could have possibly used SourceSet.getTaskName I think but its clearly not really intended for this usecase.

Comment (Juuxel) [reply src/main/java/net/fabricmc/loom/util/Strings.java:28]: I used it originally but I need the `main` source set name in this case, otherwise it'd conflict with the generic `modCompileClasspath` used for all compile cp mods.

**Review by modmuss50 — APPROVED** [review]
Looks great, tests are also useful 👍
